### ISSUE TITLE
README

### ISSUE THREAD

**Issue by garyrussell** [spring-projects/spring-bus#4]
> Note: since the same naming conventions are used in XD, you can spy on or send messages to an existing XD stream by copying the stream name (to spring.bus.group) and knowing the index of the XD module you want to interact with.

This wouldn't really "spy on", it would steal messages from the stream, right?

**Comment by dsyer** [comment]
Correct. You could spy with a tap I guess.

**Comment by dsyer** [comment]
Merged in spring-cloud-streams
